/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const API_BASE_URL: typeof import('./utils/fetcher').API_BASE_URL
  const EffectScope: typeof import('vue').EffectScope
  const areaChartOptions: typeof import('./utils/apexDefaults').areaChartOptions
  const baseOptions: typeof import('./utils/apexDefaults').baseOptions
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const fetcher: typeof import('./utils/fetcher').fetcher
  const financialColors: typeof import('./utils/apexDefaults').financialColors
  const formatDateAsMMYYYY: typeof import('./utils/date').formatDateAsMMYYYY
  const formatRelativeTime: typeof import('./utils/date').formatRelativeTime
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getScenarioValue: typeof import('./types/financial').getScenarioValue
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const lineDifferentiation: typeof import('./utils/apexDefaults').lineDifferentiation
  const markRaw: typeof import('vue').markRaw
  const mergeChartOptions: typeof import('./utils/apexDefaults').mergeChartOptions
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const patternFill: typeof import('./utils/apexDefaults').patternFill
  const pieChartOptions: typeof import('./utils/apexDefaults').pieChartOptions
  const provide: typeof import('vue').provide
  const ptViewMerge: typeof import('./volt/utils').ptViewMerge
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const registerToastServiceGlobal: typeof import('./stores/toast').registerToastServiceGlobal
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const showToast: typeof import('./stores/toast').showToast
  const softColorPalette: typeof import('./utils/apexDefaults').softColorPalette
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useApp: typeof import('./stores/main').useApp
  const useArchiveStore: typeof import('./stores/archive').useArchiveStore
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./stores/authStore').useAuthStore
  const useChatStore: typeof import('./stores/chat').useChatStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useKnowledgeBaseStore: typeof import('./stores/knowledgeBase').useKnowledgeBaseStore
  const useKnowledgeChunksStore: typeof import('./stores/knowledgeChunks').useKnowledgeChunksStore
  const useKnowledgeGroupsStore: typeof import('./stores/knowledgeGroups').useKnowledgeGroupsStore
  const useKnowledgeTextsStore: typeof import('./stores/knowledgeTexts').useKnowledgeTextsStore
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useNotificationStore: typeof import('./stores/notifications').useNotificationStore
  const useNotificationsStore: typeof import('./stores/notifications').useNotificationsStore
  const useRecordingStore: typeof import('./stores/recording').useRecordingStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSettingsStore: typeof import('./stores/settings').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ArchiveEntry } from './stores/archive'
  import('./stores/archive')
  // @ts-ignore
  export type { Role, ChatMessage } from './stores/chat'
  import('./stores/chat')
  // @ts-ignore
  export type { KnowledgeText, KnowledgeTextInsert, KnowledgeTextUpdate } from './stores/knowledgeTexts'
  import('./stores/knowledgeTexts')
  // @ts-ignore
  export type { Team } from './stores/main'
  import('./stores/main')
  // @ts-ignore
  export type { Notification } from './stores/notifications'
  import('./stores/notifications')
  // @ts-ignore
  export type { KnowledgeChunk } from './types/knowledge-chunk'
  import('./types/knowledge-chunk')
  // @ts-ignore
  export type { DefaultTypes, KnowledgeEntry, KnowledgeEntryWithText, KnowledgeFilters, KnowledgeFilter, Filter, KnowledgeFilterGroupsFromServer, KnowledgeFilterGroups, KnowledgeAssignmentType, KnowledgeAssignment, result, PostProcessor } from './types/knowledge'
  import('./types/knowledge')
  // @ts-ignore
  export type { KnowledgeGroup, KnowledgeGroupTeam } from './types/knowledgeGroup'
  import('./types/knowledgeGroup')
}
