/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedOwl: typeof import('./components/AnimatedOwl.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    Avatar: typeof import('./volt/Avatar.vue')['default']
    Badge: typeof import('./volt/Badge.vue')['default']
    Breadcrumb: typeof import('./volt/Breadcrumb.vue')['default']
    Button: typeof import('./volt/Button.vue')['default']
    Card: typeof import('./volt/Card.vue')['default']
    Checkbox: typeof import('./volt/Checkbox.vue')['default']
    Chip: typeof import('./volt/Chip.vue')['default']
    ConfirmDialog: typeof import('./volt/ConfirmDialog.vue')['default']
    DataTable: typeof import('./volt/DataTable.vue')['default']
    DatePicker: typeof import('./volt/DatePicker.vue')['default']
    Default: typeof import('./components/layout/Default.vue')['default']
    Dialog: typeof import('./volt/Dialog.vue')['default']
    EditOperationsList: typeof import('./components/wiki/EditOperationsList.vue')['default']
    FileUpload: typeof import('./volt/FileUpload.vue')['default']
    HankoAuth: typeof import('./components/hanko/HankoAuth.vue')['default']
    HankoLogoutButton: typeof import('./components/hanko/HankoLogoutButton.vue')['default']
    HankoProfile: typeof import('./components/hanko/HankoProfile.vue')['default']
    InputNumber: typeof import('./volt/InputNumber.vue')['default']
    InputText: typeof import('./volt/InputText.vue')['default']
    InvitationsList: typeof import('./components/user/InvitationsList.vue')['default']
    KnowledgeDetails: typeof import('./components/knowledge/KnowledgeDetails.vue')['default']
    KnowledgeEditAssignments: typeof import('./components/knowledge/KnowledgeEditAssignments.vue')['default']
    KnowledgeEntry: typeof import('./components/knowledge/KnowledgeEntry.vue')['default']
    KnowledgeList: typeof import('./components/knowledge/KnowledgeList.vue')['default']
    KnowledgeManage: typeof import('./components/knowledge/KnowledgeManage.vue')['default']
    KnowledgeSummary: typeof import('./components/knowledge/KnowledgeSummary.vue')['default']
    MarkdownEditor: typeof import('./components/knowledge/MarkdownEditor.vue')['default']
    Menu: typeof import('./volt/Menu.vue')['default']
    Message: typeof import('./volt/Message.vue')['default']
    MobileLayout: typeof import('./components/layout/MobileLayout.vue')['default']
    MultiSelect: typeof import('./volt/MultiSelect.vue')['default']
    OverlayBadge: typeof import('./volt/OverlayBadge.vue')['default']
    ProgressBar: typeof import('./volt/ProgressBar.vue')['default']
    ProtocolInput: typeof import('./components/digital-twin/ProtocolInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./volt/SecondaryButton.vue')['default']
    Select: typeof import('./volt/Select.vue')['default']
    SelectButton: typeof import('./volt/SelectButton.vue')['default']
    SideMenu: typeof import('./components/layout/SideMenu.vue')['default']
    SmartEditDialog: typeof import('./components/wiki/SmartEditDialog.vue')['default']
    Tab: typeof import('./volt/Tab.vue')['default']
    TabList: typeof import('./volt/TabList.vue')['default']
    TabPanel: typeof import('./volt/TabPanel.vue')['default']
    TabPanels: typeof import('./volt/TabPanels.vue')['default']
    Tabs: typeof import('./volt/Tabs.vue')['default']
    Textarea: typeof import('./volt/Textarea.vue')['default']
    Toast: typeof import('./volt/Toast.vue')['default']
    ToggleButton: typeof import('./volt/ToggleButton.vue')['default']
    ToggleSwitch: typeof import('./volt/ToggleSwitch.vue')['default']
    TranscriptionRecorder: typeof import('./components/transcription/TranscriptionRecorder.vue')['default']
    WelcomeTile: typeof import('./components/dashboard/WelcomeTile.vue')['default']
    WikiTree: typeof import('./components/wiki/WikiTree.vue')['default']
    WikiTreeNode: typeof import('./components/wiki/WikiTreeNode.vue')['default']
  }
}
